
version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17

jobs:
  sonar_analysis:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run SonarQube analysis
          command: npm run sonar
      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-cache-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  test_and_analyze:
    jobs:
      - sonar_analysis

